var div = document.getElementById("splashscreen");
div.id = "splashscreen";
div.style.width = "100%";
div.style.height = "100%";
div.style.position = "fixed";
div.style.top = "0";
div.style.bottom = "0";
div.style.right = "0";
div.style.left = "0";
div.style.display = "flex";
div.style.justifyContent = "center";
div.style.alignItems = "center";
div.style.backgroundColor = "#000080";
div.style.background = "linear-gradient(#ff0000, #0000ff)";
var img = document.createElement("img");
img.width = "64";
img.height = "64";
img.src = "images/pedestriansos_64.png";
var div2 = document.createElement("div");
div2.style.backgroundColor = "#ffffff80";
div2.style.borderRadius = "50%";
div2.style.padding = "2%";
div2.appendChild(img);
div.appendChild(div2);